---
- name: Install core packages for virtual machines
  hosts: all
  become: true

  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - nfs-common
          - qemu-guest-agent
          - inetutils-ping
          - nano
          - htop
          - cron
        update_cache: true

    - name: Start guest qemu-guest-agent
      ansible.builtin.service:
        name: qemu-guest-agent
        state: started
        enabled: true
